### ISSUE TITLE
Error building proxy on ppc64le

### ISSUE THREAD

**Issue by snehagg24** [Maistra/proxy#55]
OS: Centos 8
Installed Dependencies with version :-

[root@4801cef67c88 /]# g++ --version
g++ (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@4801cef67c88 /]# gcc --version
gcc (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@4801cef67c88 /]# go version
go version go1.13.15 linux/ppc64le
[root@4801cef67c88 /]# bazel --version
bazel 3.4.1- (@non-git)
[root@4801cef67c88 /]# ninja --version
1.8.2
[root@4801cef67c88 /]# python --version
Python 3.6.8

Bazel build argument:-
export BAZEL_BUILD_ARGS="--copt -fPIE --copt -fPIC --copt -fstack-clash-protection --copt -fplugin=annobin --copt -fstack-protector-all --copt -fstack-protector-strong --copt -O2 --copt -fexceptions --copt -D_GLIBCXX_ASSERTIONS --copt -D_GLIBCXX_USE_CXX11_ABI=0 --copt -DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 --copt -D_FORTIFY_SOURCE=2 --copt -Wno-error=deprecated-declarations --copt -Wno-error=unused-variable --copt -w --copt -ldl --host_force_python=PY3 --host_javabase=@bazel_tools//tools/jdk:absolute_javabase --define=ABSOLUTE_JAVABASE=/etc/alternatives/java_sdk/ --force_pic=true --sandbox_debug --verbose_failures --cxxopt -w"

Build command:-
make -f Makefile.core.mk BUILD_WITH_CONTAINER=0 build

Build failure error:-
`ERROR: /root/istio_build/proxy/extensions/common/BUILD:103:14: C++ compilation of rule '//extensions/common:istio_dimensions_test_lib_internal_only' failed (Exit 1): process-wrapper failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/sandbox/processwrapper-sandbox/1286/execroot/io_istio_proxy && \
  exec env - \
    CC=/opt/rh/gcc-toolset-9/root/usr/bin/gcc \
    CXX=/opt/rh/gcc-toolset-9/root/usr/bin/g++ \
    PATH=/usr/lib/llvm-9/bin:/opt/rh/gcc-toolset-9/root/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/golang/bin:/root/go/bin:/root/istio_build//gn/out \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/580c60071d0d344933e32e6e0902c535/process-wrapper '--timeout=0' '--kill_delay=15' --wait_fix /opt/rh/gcc-toolset-9/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/ppc-fastbuild/bin/extensions/common/_objs/istio_dimensions_test_lib_internal_only/istio_dimensions_test.pic.d '-frandom-seed=bazel-out/ppc-fastbuild/bin/extensions/common/_objs/istio_dimensions_test_lib_internal_only/istio_dimensions_test.pic.o' -fPIC -DSPDLOG_FMT_EXTERNAL -DFMT_HEADER_ONLY -D__CLANG_SUPPORT_DYN_ANNOTATION__ '-DGTEST_HAS_ABSL=1' -iquote . -iquote bazel-out/ppc-fastbuild/bin -iquote external/envoy -iquote bazel-out/ppc-fastbuild/bin/external/envoy -iquote external/com_google_absl -iquote bazel-out/ppc-fastbuild/bin/external/com_google_absl -iquote external/com_github_fmtlib_fmt -iquote bazel-out/ppc-fastbuild/bin/external/com_github_fmtlib_fmt -iquote external/com_github_gabime_spdlog -iquote bazel-out/ppc-fastbuild/bin/external/com_github_gabime_spdlog -iquote external/com_google_googletest -iquote bazel-out/ppc-fastbuild/bin/external/com_google_googletest -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/common/_virtual_includes/base_includes -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/fmt_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/network/_virtual_includes/address_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/network/_virtual_includes/io_handle_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/api/_virtual_includes/io_error_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/assert_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/minimal_logger_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/base_logger_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/lock_guard_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/thread_annotations -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/thread/_virtual_includes/thread_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/macros -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/non_copyable -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/logger_impl_lib_standard -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/api/_virtual_includes/os_sys_calls_interface -isystem external/com_github_fmtlib_fmt/include -isystem bazel-out/ppc-fastbuild/bin/external/com_github_fmtlib_fmt/include -isystem external/com_github_gabime_spdlog/include -isystem bazel-out/ppc-fastbuild/bin/external/com_github_gabime_spdlog/include -isystem bazel-out/ppc-fastbuild/bin/external/envoy/bazel/foreign_cc/gperftools_build/include -isystem external/com_google_googletest/googlemock -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googlemock -isystem external/com_google_googletest/googlemock/include -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googlemock/include -isystem external/com_google_googletest/googletest -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googletest -isystem external/com_google_googletest/googletest/include -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googletest/include -fPIC -DNULL_PLUGIN -fPIE -fPIC -fstack-clash-protection '-fplugin=annobin' -fstack-protector-all -fstack-protector-strong -O2 -fexceptions -D_GLIBCXX_ASSERTIONS '-D_GLIBCXX_USE_CXX11_ABI=0' '-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1' '-D_FORTIFY_SOURCE=2' '-Wno-error=deprecated-declarations' '-Wno-error=unused-variable' -w -ldl -Wnon-virtual-dtor -Wformat -Wformat-security '-D_GLIBCXX_USE_CXX11_ABI=1' '-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1' '-D_FORTIFY_SOURCE=2' '-Wno-error=deprecated-declarations' '-Wno-error=unused-variable' -w -ldl -w -Wall -Wextra -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wold-style-cast -Wformat -Wformat-security -Wvla '-std=c++14' -DTCMALLOC -DENVOY_HANDLE_SIGNALS -DENVOY_OBJECT_TRACE_ON_DUMP -DENVOY_HOT_RESTART -DENVOY_GOOGLE_GRPC -DENVOY_NORMALIZE_PATH_BY_DEFAULT -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c extensions/common/istio_dimensions_test.cc -o bazel-out/ppc-fastbuild/bin/extensions/common/_objs/istio_dimensions_test_lib_internal_only/istio_dimensions_test.pic.o) process-wrapper failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/sandbox/processwrapper-sandbox/1286/execroot/io_istio_proxy && \
  exec env - \
    CC=/opt/rh/gcc-toolset-9/root/usr/bin/gcc \
    CXX=/opt/rh/gcc-toolset-9/root/usr/bin/g++ \
    PATH=/usr/lib/llvm-9/bin:/opt/rh/gcc-toolset-9/root/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/golang/bin:/root/go/bin:/root/istio_build//gn/out \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/580c60071d0d344933e32e6e0902c535/process-wrapper '--timeout=0' '--kill_delay=15' --wait_fix /opt/rh/gcc-toolset-9/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/ppc-fastbuild/bin/extensions/common/_objs/istio_dimensions_test_lib_internal_only/istio_dimensions_test.pic.d '-frandom-seed=bazel-out/ppc-fastbuild/bin/extensions/common/_objs/istio_dimensions_test_lib_internal_only/istio_dimensions_test.pic.o' -fPIC -DSPDLOG_FMT_EXTERNAL -DFMT_HEADER_ONLY -D__CLANG_SUPPORT_DYN_ANNOTATION__ '-DGTEST_HAS_ABSL=1' -iquote . -iquote bazel-out/ppc-fastbuild/bin -iquote external/envoy -iquote bazel-out/ppc-fastbuild/bin/external/envoy -iquote external/com_google_absl -iquote bazel-out/ppc-fastbuild/bin/external/com_google_absl -iquote external/com_github_fmtlib_fmt -iquote bazel-out/ppc-fastbuild/bin/external/com_github_fmtlib_fmt -iquote external/com_github_gabime_spdlog -iquote bazel-out/ppc-fastbuild/bin/external/com_github_gabime_spdlog -iquote external/com_google_googletest -iquote bazel-out/ppc-fastbuild/bin/external/com_google_googletest -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/common/_virtual_includes/base_includes -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/fmt_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/network/_virtual_includes/address_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/network/_virtual_includes/io_handle_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/api/_virtual_includes/io_error_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/assert_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/minimal_logger_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/base_logger_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/lock_guard_lib -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/thread_annotations -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/thread/_virtual_includes/thread_interface -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/macros -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/non_copyable -Ibazel-out/ppc-fastbuild/bin/external/envoy/source/common/common/_virtual_includes/logger_impl_lib_standard -Ibazel-out/ppc-fastbuild/bin/external/envoy/include/envoy/api/_virtual_includes/os_sys_calls_interface -isystem external/com_github_fmtlib_fmt/include -isystem bazel-out/ppc-fastbuild/bin/external/com_github_fmtlib_fmt/include -isystem external/com_github_gabime_spdlog/include -isystem bazel-out/ppc-fastbuild/bin/external/com_github_gabime_spdlog/include -isystem bazel-out/ppc-fastbuild/bin/external/envoy/bazel/foreign_cc/gperftools_build/include -isystem external/com_google_googletest/googlemock -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googlemock -isystem external/com_google_googletest/googlemock/include -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googlemock/include -isystem external/com_google_googletest/googletest -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googletest -isystem external/com_google_googletest/googletest/include -isystem bazel-out/ppc-fastbuild/bin/external/com_google_googletest/googletest/include -fPIC -DNULL_PLUGIN -fPIE -fPIC -fstack-clash-protection '-fplugin=annobin' -fstack-protector-all -fstack-protector-strong -O2 -fexceptions -D_GLIBCXX_ASSERTIONS '-D_GLIBCXX_USE_CXX11_ABI=0' '-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1' '-D_FORTIFY_SOURCE=2' '-Wno-error=deprecated-declarations' '-Wno-error=unused-variable' -w -ldl -Wnon-virtual-dtor -Wformat -Wformat-security '-D_GLIBCXX_USE_CXX11_ABI=1' '-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1' '-D_FORTIFY_SOURCE=2' '-Wno-error=deprecated-declarations' '-Wno-error=unused-variable' -w -ldl -w -Wall -Wextra -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wold-style-cast -Wformat -Wformat-security -Wvla '-std=c++14' -DTCMALLOC -DENVOY_HANDLE_SIGNALS -DENVOY_OBJECT_TRACE_ON_DUMP -DENVOY_HOT_RESTART -DENVOY_GOOGLE_GRPC -DENVOY_NORMALIZE_PATH_BY_DEFAULT -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c extensions/common/istio_dimensions_test.cc -o bazel-out/ppc-fastbuild/bin/extensions/common/_objs/istio_dimensions_test_lib_internal_only/istio_dimensions_test.pic.o)
In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:62,
                 from external/com_google_googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:47,
                 from external/com_google_googletest/googlemock/include/gmock/gmock-actions.h:51,
                 from external/com_google_googletest/googlemock/include/gmock/gmock.h:59,
                 from external/com_google_absl/absl/hash/hash_testing.h:23,
                 from extensions/common/istio_dimensions_test.cc:18:
extensions/common/istio_dimensions_test.cc: In member function 'virtual void Wasm::Common::{anonymous}::WasmCommonIstioDimensionsTest_VerifyHashing_Test::TestBody()':
extensions/common/istio_dimensions_test.cc:31:77: error: designator order for field 'Wasm::Common::IstioDimensions::source_app' does not match declaration order in 'Wasm::Common::IstioDimensions'
   31 |       IstioDimensions{.request_protocol = "grpc", .source_app = "app_source"},
      |                                                                             ^
extensions/common/istio_dimensions_test.cc:34:45: error: designator order for field 'Wasm::Common::IstioDimensions::source_app' does not match declaration order in 'Wasm::Common::IstioDimensions'
   34 |                       .source_version = "v2"},
      |                                             ^
extensions/common/istio_dimensions_test.cc:38:45: error: designator order for field 'Wasm::Common::IstioDimensions::request_protocol' does not match declaration order in 'Wasm::Common::IstioDimensions'
   38 |                       .source_version = "v2"},
      |                                             ^
extensions/common/istio_dimensions_test.cc:42:45: error: designator order for field 'Wasm::Common::IstioDimensions::request_protocol' does not match declaration order in 'Wasm::Common::IstioDimensions'
   42 |                       .source_version = "v2"},
      |                                             ^
extensions/common/istio_dimensions_test.cc:47:51: error: designator order for field 'Wasm::Common::IstioDimensions::request_protocol' does not match declaration order in 'Wasm::Common::IstioDimensions'
   47 |                       .grpc_response_status = "12"},
      |                                                   ^
INFO: Elapsed time: 844.924s, Critical Path: 612.00s
INFO: 1288 processes: 1287 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
make: *** [Makefile.core.mk:68: build] Error 1`

**Comment by jwendell** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
