### ISSUE TITLE
Maistra images for arm64

### ISSUE THREAD

**Issue by nak3** [Maistra/proxy#92]
Currently maistra does not publish other platform images like arm64.
For example, I looked at https://hub.docker.com/r/maistra/proxyv2-ubi8 but could not see any other arch except for amd64.

We would like to request publish arm64 or other architecture images.

**Comment by jwendell** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)

**Comment by nak3** [comment]
Alright. Opened https://issues.redhat.com/browse/MAISTRA-2108
